server:
    port: 8083
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: movie-rating-service
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/rating/**
                - id: movie-info-service
                  uri: http://localhost:8082/
                  predicates:
                      - Path=/movies/**
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    registerWithEureka:
        - true
    fetchRegistry:
        - true
